# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`

# Prevent notifications or newly active windows from stealing focus while typing.
input {
    follow_mouse = 0
}

misc {
    focus_on_activate = false
    mouse_move_focuses_monitor = false
}

cursor {
    no_warps = true
}
